---
- name: 
  remote_user: root
  hosts: test
  tasks:
  # ping服务器
    - name: ping server
      ping:
        data: pong 
    - name: ensure required pip-packages are installed
      pip:
        name: 
          - docker>=1.8.0
          - PyYAML>=3.11
          - docker-compose>=1.7.0