- name: ping
  ping:
    data: pong # not required. Data to return for the C(ping) return value. If this parameter is set to C(crash), the module will cause an exception.

- name: copy shell file
  copy: 
    dest: /etc/ansible/demo # required. Remote absolute path where the file should be copied to. If C(src) is a directory, this must be a directory too. If C(dest) is a non-existent path and if either C(dest) ends with "/" or C(src) is a directory, C(dest) is created. If I(dest) is a relative path, the starting directory is determined by the remote host. If C(src) and C(dest) are files, the parent directory of C(dest) is not created and the task fails if it does not already exist.
    src: some.sh # not required. Local path to a file to copy to the remote server. This can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to the C(rsync) command line tool.

- name: config crontab 
  cron:
    name:  
    user:  
    job:  
    state: absent # not required. choices: absent;present. Whether to ensure the job or environment variable is present or absent.
    cron_file:  # not required. If specified, uses this file instead of an individual user's crontab. If this is a relative path, it is interpreted with respect to I(/etc/cron.d). If it is absolute, it will typically be I(/etc/crontab). Many linux distros expect (and some require) the filename portion to consist solely of upper- and lower-case letters, digits, underscores, and hyphens. To use the C(cron_file) parameter you must specify the C(user) as well.
    backup: False # not required. If set, create a backup of the crontab before it is modified. The location of the backup is returned in the C(backup_file) variable by this module.
    minute: 00 
    hour: 00 
    day: * 
    month: * 
    weekday: 7 

  notify: #事件
    - restart server
    - check nginx